title = "the test script to test a model on cast20 benchmarks"

# [Model]
query_encoder_checkpoint = "checkpoints/ad-hoc-ance-msmarco"   # !!!
# query_encoder_checkpoint = "output/train_topiocqa/filter/FR_model-4-epoch-9-step-14210-loss-1.5144615173339844"   # !!!
pretrained_passage_encoder = "checkpoints/ad-hoc-ance-msmarco"   # !!!

max_concat_length = 512
max_query_length = 64
max_doc_length = 384
seed = 42

# [Model]
# model_type = "ANCE_context_attention"
model_type = "ANCE"

# [Test]

# since the passage collection is too big, we split it into several blocks and test block by block.
# Finally merge them to get the final results.
passage_block_num = 16 # 16 for cast

per_gpu_eval_batch_size = 2
n_gpu = 1
use_gpu = true
top_n = 100
use_data_percent = 1
rel_threshold = 1
cross_validate = false
disable_tqdm = false
use_last_response = false
use_PRF = false
PRF_mode = "hard"
test_type = "rewrite"
eval_type = "oracle"


#test_file_path = "datasets/cast19/eval_topics.jsonl"
test_file_path = "output/cast19/QR/test_QRIR_KD_oracle_0.5_prefix.json"
test_file_path_2 = "output/cast19/QR/test_QRIR_KD_answer_0.5_prefix.json"
trec_gold_qrel_file_path = "datasets/cast19/qrels.tsv"
PRF_file = "output/cast19/dense_rel/dev_rel_label_ndcg_rawq.json"
#PRF_file = "datasets/cast19/eval_topics_human.jsonl"


passage_collection_path= "datasets/cast20/collection.tsv"
passage_embeddings_dir_path = "datasets/cast20/embeds"
passage_offset2pid_path = "datasets/cast20/tokenized/offset2pid.pickle"

# [Output]
qrel_output_path = "output/cast19/baseline_conv"   
